FROM golang:1.19.5-alpine3.17 as builder

WORKDIR /build
COPY ./ .

RUN cd examples/http-server && go build

FROM alpine:3.17

COPY --from=builder /build/examples/http-server/http-server /

CMD /http-server
